### ISSUE TITLE
Error on attempting to import ipyradiant

### ISSUE THREAD

**Issue by DManowitz** [jupyrdf/ipyradiant#129]
After installing ipyradiant from conda-forge into a new conda environment, I get the following error on trying to import it:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\manow\miniconda3\envs\py37_ipyradiant_test\lib\site-packages\ipyradiant\__init__.py", line 13, in <module>
    from .loader import FileManager, PathLoader, UpLoader
  File "C:\Users\manow\miniconda3\envs\py37_ipyradiant_test\lib\site-packages\ipyradiant\loader\__init__.py", line 7, in <module>
    from .manager import FileManager
  File "C:\Users\manow\miniconda3\envs\py37_ipyradiant_test\lib\site-packages\ipyradiant\loader\manager.py", line 10, in <module>
    from .base import BaseLoader
  File "C:\Users\manow\miniconda3\envs\py37_ipyradiant_test\lib\site-packages\ipyradiant\loader\base.py", line 9, in <module>
    from .util import guess_format
  File "C:\Users\manow\miniconda3\envs\py37_ipyradiant_test\lib\site-packages\ipyradiant\loader\util.py", line 11, in <module>
    SUFFIX_FORMAT_MAP = dict(**util.SUFFIX_FORMAT_MAP, jsonld="json-ld", json="json-ld")
TypeError: type object got multiple values for keyword argument 'jsonld'

**Comment by zwelz3** [comment]
Sorry @DManowitz, we have fixed the issue on `master`, but we are currently without funding (university affiliated) and have not been able to cut a new release.

**Comment by zwelz3** [comment]
Closed by #123
